export enum ASTTypes {
  rule = "rule",
  comment = "comment",
  media = "media",
  charset = "charset",
  customMedia = "custom-media",
  document = "document",
  fontFace = "font-face",
  host = "host",
  import = "import",
  keyframes = "keyframes",
  keyframe = "keyframe",
  namespace = "namespace",
  supports = "supports",
  declaration = "declaration",
  stylesheet = "stylesheet",
}